# -*- coding: utf-8 -*-
"""RAG_pecellelelala.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PifHHg1FsEhvYGq7aKb0nLoiOY5_9ksQ

# 🤖 RAG Onboarding Chatbot
### Pecel Lele Lala
**Final Project — AI Bootcamp**

Stack: LangChain · Groq (LLaMA 3.1) · Qdrant Cloud · SentenceTransformers · Streamlit

---

## Cell 1 — Install Libraries
"""

!pip install langchain langchain-community langchain-text-splitters pymupdf sentence-transformers qdrant-client groq rouge-score -q

"""## Cell 2 — Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""## Cell 3 — Konfigurasi Perusahaan
> ⚙️ **GANTI BAGIAN INI** sesuai perusahaan
"""

# ============================================================
# ⚙️  KONFIGURASI — GANTI SESUAI PERUSAHAAN
# ============================================================
COMPANY_NAME    = "Pecel Lele Lala"
FOLDER_PATH     = "/content/drive/MyDrive/Colab Notebooks/FinalProject_AI_Bootcamp/Data/Input/Pecel Lele Lala"
COLLECTION_NAME = "pecel_lele_lala"
# ============================================================

print(f"✅ Konfigurasi: {COMPANY_NAME}")
print(f"📁 Folder     : {FOLDER_PATH}")
print(f"🗄️  Collection : {COLLECTION_NAME}")

"""## Cell 4 — Load API Keys"""

from google.colab import userdata
import os

os.environ["GROQ_API_KEY"]    = userdata.get("GROQ_API_KEY")
os.environ["QDRANT_URL"]      = userdata.get("QDRANT_URL")
os.environ["QDRANT_API_KEY"]  = userdata.get("QDRANT_API_KEY")

print("✅ Semua API Key loaded!")

"""## Cell 5 — Load & Chunk PDF"""

from langchain_community.document_loaders import PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load PDF
pdf_files = [f for f in os.listdir(FOLDER_PATH) if f.endswith(".pdf")]
all_documents = []

for pdf_file in pdf_files:
    pdf_path = os.path.join(FOLDER_PATH, pdf_file)
    loader = PyMuPDFLoader(pdf_path)
    docs = loader.load()
    for doc in docs:
        doc.metadata["company"] = COMPANY_NAME
    all_documents.extend(docs)
    print(f"✅ {pdf_file} ({len(docs)} halaman)")

print(f"\n📄 Total halaman: {len(all_documents)}")

# Chunking
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50,
    separators=["\n\n", "\n", ".", " ", ""]
)
all_chunks = text_splitter.split_documents(all_documents)
print(f"🧩 Total chunks: {len(all_chunks)}")

"""## Cell 6 — Load Embedding Model"""

from sentence_transformers import SentenceTransformer

print("⏳ Loading embedding model...")
embedder = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
print("✅ Embedding model loaded!")

"""## Cell 7 — Connect & Upload ke Qdrant Cloud"""

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct, PayloadSchemaType

# Connect
qdrant = QdrantClient(
    url=os.environ["QDRANT_URL"],
    api_key=os.environ["QDRANT_API_KEY"],
)
print("✅ Terhubung ke Qdrant Cloud!")

# Reset collection
if qdrant.collection_exists(COLLECTION_NAME):
    qdrant.delete_collection(COLLECTION_NAME)
    print("🗑️  Collection lama dihapus")

qdrant.create_collection(
    collection_name=COLLECTION_NAME,
    vectors_config=VectorParams(size=384, distance=Distance.COSINE)
)

# Buat index untuk filter
qdrant.create_payload_index(
    collection_name=COLLECTION_NAME,
    field_name="company",
    field_schema=PayloadSchemaType.KEYWORD
)
print("✅ Collection & index siap!")

# Embed & upload
texts     = [chunk.page_content for chunk in all_chunks]
metadatas = [chunk.metadata for chunk in all_chunks]
print(f"⏳ Embedding {len(texts)} chunks...")
embeddings = embedder.encode(texts, show_progress_bar=True)

points = [
    PointStruct(
        id=i,
        vector=embeddings[i].tolist(),
        payload={"text": texts[i], **metadatas[i]}
    )
    for i in range(len(texts))
]

qdrant.upsert(collection_name=COLLECTION_NAME, points=points)
print(f"\n✅ {len(points)} chunks tersimpan di Qdrant Cloud!")

"""## Cell 8 — Fungsi RAG Chat"""

from groq import Groq

groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])

def rag_chat(pertanyaan: str, top_k: int = 5):
    # 1. Embed pertanyaan
    query_vector = embedder.encode(pertanyaan).tolist()

    # 2. Cari chunks relevan di Qdrant
    results = qdrant.query_points(
        collection_name=COLLECTION_NAME,
        query=query_vector,
        limit=top_k,
    ).points

    # 3. Susun context
    context = "\n\n".join([r.payload["text"] for r in results])

    # 4. Generate jawaban
    response = groq_client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "system",
                "content": f"""Kamu adalah asisten onboarding karyawan baru di {COMPANY_NAME}.
Jawab pertanyaan HANYA berdasarkan konteks dokumen internal perusahaan yang diberikan.
Gunakan bahasa Indonesia yang ramah dan mudah dipahami.
Jika informasi tidak ada di konteks, katakan dengan jujur bahwa kamu tidak tahu."""
            },
            {
                "role": "user",
                "content": f"KONTEKS:\n{context}\n\nPERTANYAAN:\n{pertanyaan}"
            }
        ]
    )
    return response.choices[0].message.content, results

print(f"✅ Fungsi rag_chat siap untuk {COMPANY_NAME}!")

"""## Cell 9 — Test Chatbot"""

# Ganti pertanyaan sesuai kebutuhan
pertanyaan = "Siapa kita dan apa yang kita lakukan?"

jawaban, sources = rag_chat(pertanyaan)
print(f"❓ Pertanyaan: {pertanyaan}")
print(f"\n💬 Jawaban:")
print(jawaban)
print(f"\n📚 Dari {len(sources)} chunks relevan")

# ============================================================
# 💬 CELL TEST — Ketik pertanyaan kamu di sini!
# ============================================================

pertanyaan = input(f"❓ Tanya sesuatu tentang {COMPANY_NAME}: ")

jawaban, sources = rag_chat(pertanyaan)

print(f"\n💬 Jawaban:")
print("─" * 60)
print(jawaban)
print("─" * 60)
print(f"📚 Dari {len(sources)} chunks relevan")

"""## Cell 10 — EVALUASI"""

from rouge_score import rouge_scorer

# ============================================================
# 📊 DATA EVALUASI — Pertanyaan + Jawaban Referensi
# ============================================================
eval_data = [
    {
        "pertanyaan": "Apa visi dan misi perusahaan?",
        "referensi": "Perusahaan memiliki visi dan misi yang menjadi landasan operasional dan pelayanan kepada pelanggan."
    },
    {
        "pertanyaan": "Sebutkan produk atau layanan utama perusahaan.",
        "referensi": "Perusahaan menyediakan produk dan layanan utama sesuai bidang usaha yang tercantum di dokumen internal."
    },
    {
        "pertanyaan": "Bagaimana standar pelayanan kepada pelanggan?",
        "referensi": "Karyawan wajib memberikan pelayanan yang ramah, cepat, dan profesional kepada setiap pelanggan."
    },
    {
        "pertanyaan": "Apa saja peraturan kerja karyawan?",
        "referensi": "Karyawan wajib mematuhi peraturan kerja yang ditetapkan perusahaan termasuk jadwal dan standar perilaku."
    },
    {
        "pertanyaan": "Bagaimana struktur organisasi perusahaan?",
        "referensi": "Perusahaan memiliki struktur organisasi yang jelas dengan pembagian tugas dan tanggung jawab tiap jabatan."
    },
]
# ============================================================

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=False)

print(f"📊 Evaluasi ROUGE — {COMPANY_NAME}")
print("=" * 70)

total_r1, total_r2, total_rL = 0, 0, 0

for i, item in enumerate(eval_data):
    jawaban_chatbot, _ = rag_chat(item["pertanyaan"])
    scores = scorer.score(item["referensi"], jawaban_chatbot)

    r1 = scores['rouge1'].fmeasure
    r2 = scores['rouge2'].fmeasure
    rL = scores['rougeL'].fmeasure

    total_r1 += r1
    total_r2 += r2
    total_rL += rL

    print(f"\n❓ Q{i+1}: {item['pertanyaan']}")
    print(f"   ROUGE-1: {r1:.4f} | ROUGE-2: {r2:.4f} | ROUGE-L: {rL:.4f}")

n = len(eval_data)
print("\n" + "=" * 70)
print(f"📈 RATA-RATA ROUGE SCORE — {COMPANY_NAME}")
print(f"   ROUGE-1 : {total_r1/n:.4f}")
print(f"   ROUGE-2 : {total_r2/n:.4f}")
print(f"   ROUGE-L : {total_rL/n:.4f}")
print("=" * 70)